### ISSUE TITLE
Request for more info about supported FPGAs

### ISSUE THREAD

**Issue by ndbroadbent** [zephray/VerilogBoy#10]
Hello! This is such an awesome project. Nice work!

I saw in the README:

> Currently targeting on Xilinx ML505/XUPV5 and Terasic DE10-Lite. A dedicated handheld is in developement.

I found that the Xilinx ML505 board isn't being sold any more, but it uses a Virtex-5 LXT chip with 46K LEs. The [DE10-Lite](http://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=english&No=1021) is really affordable, and I saw that it has a Altera MAX 10 with 50K LEs.

The reason I'm asking is because I'm updating my ["Best FPGA dev boards" post on /r/FPGA](https://www.reddit.com/r/FPGA/comments/9yutk8/best_100300_fpga_development_board_in_2018/), and I'm adding a link to VerilogBoy at the bottom. I'd like to know which FPGAs should have enough LUTs to run this.

Also I've just ordered a [numato Mimas A7](https://numato.com/product/mimas-a7-artix-7-fpga-development-board-with-ddr-sdram-and-gigabit-ethernet) with an Artix 7 FPGA that has 52K LEs. So I'm guessing VerilogBoy should be able to run on an Artix 7?

I also ordered a [iCE40-HX8K Breakout Board](http://www.latticesemi.com/en/Products/DevelopmentBoardsAndKits/iCE40HX8KBreakoutBoard.aspx), but this only has 7K LEs, so I'm assuming this won't be enough to run VerilogBoy. But it would be helpful to know how many LEs are actually required.

Thanks!

**Comment by zephray** [comment]
Around 10K LEs are actually required to run the VerilogBoy, you might get some luck porting it to iCE40-HX8K board. Since everything in the refactor branch is WIP, I would suggest you switch to the master branch which contains a fully working ML505 port.

**Comment by ndbroadbent** [comment]
Ok great, thank for your help! I will use the master branch for now. I look forward to getting my FPGA dev board and trying it out!
