### ISSUE TITLE
Are you aware of the MiST and MiSTer projects ? 

### ISSUE THREAD

**Issue by brNX** [zephray/VerilogBoy#16]
Hi, 

I just wanted to ask if you aware of the MiST and/or MiSTer projects. 
There's is already working fpga implementation of the Gameboy for those (not perfect yet) , I recently started fixing things (audio, irq and cpu bugs mostly) on the MiSTer GB core and added GBC support. 

https://github.com/MiSTer-devel/Gameboy_MiSTer

And btw good job, looking forward to see the handheld version working

Cheers

**Comment by zephray** [comment]
Hi,

Sure I am aware of the MiST and MiSTer, I really like the idea behind that. I read through the MiST's Gameboy core code after I finished my first revision here. Unfortunately I don't own either MiST or DE10-nano, so I never tried it myself.

Thank you for sharing your work, looks great! Please make a demo video after things are working :)

Regards

**Comment by brNX** [comment]
Hi , 
I don't have a capture card but you can check out nml32 , indcision and smokemonster's youtube channels:

https://www.youtube.com/watch?v=qPKIYTElJMs&t=2132s
https://youtu.be/V-DpxgH2fbY?t=1007
https://www.youtube.com/user/indcsion/search?query=gameboy
https://www.youtube.com/user/NML32/search?query=gameboy

there has been some improvements since then and a lot of filters added.

Regards
