### ISSUE TITLE
Super Mario Land hangs when entering bonus game

### ISSUE THREAD

**Issue by blazer82** [zephray/VerilogBoy#29]
As you know, I use your VerilogBoy with real cartridges instead of ROM images and I ran into an issue with _Super Mario Land_ that I'm not sure where it's originating.

**_Issue_**

When _Super Mario Land_ is supposed to enter the bonus game (triggered by exiting through the upper door in level 1 and 2 or by finishing level 3), the execution of the game hangs.

So far I have determined that:

- The execution is caught up in a loop between PC `0x97` and `0x9C` which is basically the following loop:

```
LDH A, [$FF41]
ADD $03
JR NZ, $FA
```

- The loop waits for an HSYNC to occur that just won't happen.
- The _stat register_ at `0xFF41` keeps a constant value of `0x41` and the PPU state stays on `s_IDLE` forever.

**_Steps to reproduce_**

Exit level 1 or 2 through the upper door or finish level 3.

**_Further considerations_**

I'm not sure yet whether this is a general issue with VerilogBoy or whether this only arises when using real cartridges. It may be helpful to know if you can reproduce this behavior at all.

I'll keep looking for the root cause but any suggestions on what might be the issue are very welcome 😊

**Comment by zephray** [comment]
Hi, thanks for the feedback. My initial guess would be that's a bug in the PPU. While the CPU/ Timer/ PSG are well tested, the PPU isn't. But the fact that the PPU stays in IDLE tends to suggest that the PPU is turned off for some reason. Just by looking at the PPU logic, it would exit IDLE when vblank comes and the LCD is enabled. HV timing counter is always running regardless of the other states or registers, so the Vblank would always come. That means the LCD is disabled. So the next step would be:
1. Verify if LCD is really disabled or not. 
2. If it is disabled, should it be disabled?
3. If it should be disabled, should STAT register indicate the LCD is in VBlank or not?

**Comment by blazer82** [comment]
@zephray thanks for the very fast reply! 😊

>That means the LCD is disabled

From looking at the code, that's my current best guess, too. I'll try to verify that and if successful try to answer the to follow-up questions you mentioned.

Very helpful, thank you! I'll update this thread with any findings.

**Comment by blazer82** [comment]
>1. Verify if LCD is really disabled or not.

I confirmed that the _LCDC_ goes to `0x00`, so the LCD really is disabled at that point.

**Comment by blazer82** [comment]
I found [this reddit post](https://www.reddit.com/r/Gameboy/comments/a1c8h0/comment/eap4f8c/?context=3) that seems to suggest that

>the LCD enters Mode 0

when disabled which would provide an answer to

>3. If it should be disabled, should STAT register indicate the LCD is in VBlank or not?

while most likely also resolving the issue.

I'll be back with updates...

**Comment by blazer82** [comment]
Fixed it! I'll create a pull request.
